# Generated by Django 4.1.1 on 2022-09-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='comment',
            field=models.CharField(max_length=2000, verbose_name='コメント'),
        ),
    ]
